### ISSUE TITLE
Change license to GNU GPL to be able publish Emacs extension

### ISSUE THREAD

**Issue by EmilySeville7cfg** [tldr-pages/tldr-lint#225]
Checkout [this](https://github.com/melpa/melpa/pull/8323#issuecomment-1358310554) comment please from MELPA maintainers.

**Comment by owenvoke** [comment]
I don't think this is something we want to do... 👀

**Comment by waldyrious** [comment]
> Surely it should just be your repo that is changed to GPL.

More specifically, this: https://github.com/tldr-pages/tldr-emacs-extension

**Comment by waldyrious** [comment]
In fact, from [this comment](https://github.com/melpa/melpa/pull/8323#issuecomment-1358310554): 

> License clash (the repo is licensed with MIT but the source file has GPL boilerplate)

...and [this one](https://github.com/melpa/melpa/pull/8323#issuecomment-1358855251):

>> Do you mean that I have to change my license to GNU GPL as long as tldr-lint license?
>
> I just mean that the repository should have the same license as the elisp files (per their boilerplate). I

...it seems to me that the solution could be either changing the license of https://github.com/tldr-pages/tldr-emacs-extension to GPL, or fixing the boilerplate (found [here](https://github.com/tldr-pages/tldr-emacs-extension/blob/main/flymake-tldr-lint.el#L9-L20)) to mention MIT as opposed to GPL.

However, since that file is [based](https://github.com/tldr-pages/tldr-emacs-extension/blob/2e40d104d7f6d6c761c2c91d471f8c7413de09e7/flymake-tldr-lint.el#L24-L25) on an example from the GNU project:

> ;; Based in part on:
> ;;   https://www.gnu.org/software/emacs/manual/html_node/flymake/An-annotated-example-backend.html

...which I assume is GPL-licensed, indeed the right course of action seems to be relicensing https://github.com/tldr-pages/tldr-emacs-extension to GPL, which you already did in https://github.com/tldr-pages/tldr-emacs-extension/pull/22.

In any case, I don't see a need for tldr-lint to be GPL'd; MIT-licensed software (like tldr-lint) can be used in GPL-licensed software (like tldr-emacs-extension). It's only the opposite that isn't true. So I would suggest closing #226 without merging that change.

**Comment by EmilySeville7cfg** [comment]
Thanks for a clarification. 😄
