### ISSUE TITLE
Allow (and enforce) language-specific punctuation

### ISSUE THREAD

**Issue by bl-ue** [tldr-pages/tldr-lint#56]
The linter should allow, and enforce, the correct punctuation for all languages.  For example, Hindi ([`pages.hi`](https://github.com/tldr-pages/tldr/tree/master/pages.hi/common)) seems to use `।` as period character.  In that case, the linter should require that sentences in the page description end with that character.

TODO: add Chinese info

**Comment by waldyrious** [comment]
Can someone please reopen this, and configure the stale action so it doesn't close issues, just reminds people of them? This is especially bad because the stale-adding action was not accompanied by a comment, so even people watching this repo or this specific issue wouldn't get a notification (I don't think I got one).
